### ISSUE TITLE
os_migrate.os_migrate.import_workloads - log_file path is getting mangled and failing subsequent tasks

### ISSUE THREAD

**Issue by paulbrowne** [os-migrate/os-migrate#524] opened 2022-03-25 16:22 UTC
In the preliminary setup task of the workloads.yml playbook in the import_workloads role, part of the log_file path is emerging mangled for me as it is output from the import_workloads_prelim module and as a result subsequent import tasks are failing (due to non-existent path error) ;

```
TASK [os_migrate.os_migrate.import_workloads : preliminary setup for workload import] ******************************************************
changed: [localhost] => changed=true 
  log_file: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs/test-bastion.log
  server_name: test-bastion
  state_file: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs/test-bastion.state
Friday 25 March 2022  15:07:08 +0000 (0:00:03.739)       0:00:45.913 **********
```

This directory for log/state storage is being created correctly in the previous task, however ;

```
TASK [os_migrate.os_migrate.import_workloads : create directory for workload migration logs] ***********************************************
changed: [localhost] => changed=true 
  gid: 15080
  group: pfb29
  mode: '0750'
  owner: pfb29
  path: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/rcp-test-migration-project/workload_logs
  secontext: system_u:object_r:nfs_t:s0
  size: 2
  state: directory
  uid: 15080
```

Inserting some debug var tasks immediately prior to and after this workloads.yml preliminary setup task, the log path still seems to be being reported correctly prior, so it's only being stored incorrectly in the registered var prelim as output from the module ;

```
TASK [os_migrate.os_migrate.import_workloads : DEBUG: Write out explicit log_file path] ***********************************************************
ok: [localhost] => 
  msg: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/rcp-test-migration-project/workload_logs
Friday 25 March 2022  16:08:01 +0000 (0:00:00.096)       0:00:40.944 ********** 

TASK [os_migrate.os_migrate.import_workloads : preliminary setup for workload import] *****************************************************$
changed: [localhost] => changed=true 
  log_file: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs/test-bastion.log
  server_name: test-bastion
  state_file: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs/test-bastion.state
Friday 25 March 2022  16:08:05 +0000 (0:00:03.831)       0:00:44.775 **********

TASK [os_migrate.os_migrate.import_workloads : DEBUG: Write out explicit prelim.log_file] ********************************************************$
ok: [localhost] => 
  prelim.log_file: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs/test-bastion.log
Friday 25 March 2022  16:08:05 +0000 (0:00:00.083)       0:00:44.859 **********
```

**Comment by paulbrowne** [comment] 2022-03-25 16:37
If I hard-code the log_dir parameter in the task in workloads.yml playbook of the import_workloads.yml role, I still see the same behaviour showing up in the module invocation_args strangely, so it's a bit of a mystery where this is getting introduced at the moment ; 

```
# Hardcoded log_dir in the task
  - name: preliminary setup for workload import
    os_migrate.os_migrate.import_workload_prelim:
...
      #log_dir: "{{ os_migrate_data_dir }}/workload_logs"
      log_dir: "/home/pfb29/gitlab-uis/vss-migration/os-migrate-data/rcp-test-migration-project/workload_logs"
```

```
## Verbose output of task run, showing module invocation args
TASK [os_migrate.os_migrate.import_workloads : preliminary setup for workload import] ******************************************************
task path: /home/pfb29/.ansible/collections/ansible_collections/os_migrate/os_migrate/roles/import_workloads/tasks/workload.yml:6
changed: [localhost] => changed=true 
...
      interface: public
      log_dir: /home/pfb29/gitlab-uis/vss-migration/os-migrate-data/********/workload_logs
      region_name: RegionOne
      src_conversion_host:
```

**Comment by jistr** [comment] 2022-03-28 10:08
Hello @paulbrowne, i think you may be hitting an issue with Ansible censoring strings that appear in the credentials: https://github.com/ansible/ansible/issues/54332 

If the path component of the data directory that prints out as `******` is e.g. a user name or project name that appears in the credentials, this could be the cause. The workaround would be to rename the directory to not match the user/project.

This is a very annoying feature/bug with Ansible -- we cannot specify that only the password in the credentials dictionary should be treated as a secret, instead the whole credentials dict is marked as a secret, so all its keys/values are affected i think. We looked into this in the past, but it is not possible to fix in OS Migrate, the Ansible way of treating secrets would have to be re-thought.

Here's a similar issue: https://github.com/os-migrate/os-migrate/issues/489

**Comment by paulbrowne** [comment] 2022-03-28 21:23
Aha, thanks @jistr , I think you're probably right here as I was using the project name as a component in the full path to os-migrate project data storage (to keep separate projects separated as they're exported).

I'll try to refactor some of the bits setting that up and calling os-migrate and see if that fixes it.

Would even a sub-string be masked in this way in the full path string, if it contains the affected user/project name? If so, I'll try and use something else identifiable to the project but not contained in that dict.

**Comment by jistr** [comment] 2022-03-29 12:36
I think if the full string of project name appears as a substring somewhere, it would get masked like this, yes. It's quite uncomfortable but probably can't be fixed without redesigning how Ansible approaches `no_log` or how the OpenStack modules (not only OS Migrate but the `openstack.cloud` upstream module) deals with authentication info.

**Comment by paulbrowne** [comment] 2022-04-01 08:46
Hi @jistr , I can confirm that the presence of the sub-string still triggers the behaviour, but to get around it quickly sanitizing the project name with something like this in a pre-migration playbook setting up storage directories for os-migrate vars or data works fine to avoid it (for anyone else who might run into this) ;

```
   vars:
     pwd: "{{ lookup('env','PWD') }}"
     rcc_project: "{{ lookup('env','RCC_PROJECT') }}"
     rcc_project_sanitized: "{{ rcc_project | replace('-','_') }}"
```

**Closed** 2022-04-01 08:46 UTC
