### ISSUE TITLE
Subnet update fails

### ISSUE THREAD

**Issue by jistr** [os-migrate/os-migrate#142] opened 2020-03-27 09:45 UTC
When subnet needs to be updated, it fails with: "Cannot update read-only attribute ip_version", we probably need to drop that parameter from the update request. There may be more parameters like this.

**Comment by rbrady** [comment] 2020-03-27 12:59
Closed as a duplicate of #140 .  It has the same error message.

**Comment by jistr** [comment] 2020-03-27 13:43
There are two different bugs though so we should have 2 different issues -- one is for update_subnet getting triggered at all (which means the idempotence is broken), the other is for update_subnet failing (which means the update is broken). So we should reopen this one i think. In PR #145 you're fixing the update, but not the idempotence.

**Comment by jistr** [comment] 2020-03-31 08:56
So bug #140 should now be fixed by PR #149, but should the subnet update get triggered by a real change in a real use case, it will still fail. Bug #142 is still not fixed. Reopening.

**Closed** 2020-04-03 12:44 UTC
Labels: bug
